### PR TITLE
Features Draft with brackets removed wooo

### PR DESCRIPTION
**Pull request by mpleung93**
pull request!
pull request!

### CODE REVIEW

**Comment by dylanmoz** [comment]
Could you make the icons match somewhat to the feature you added?

For example, the line chart icon would probably go better with "Conclusion".

You can change the icons as well, the full selection is here: https://fortawesome.github.io/Font-Awesome/icons/

To change, look for the class "fa-paperclip", and change it to "fa-bicycle", for example.

You also don't need to close this pull request, pushing to your branch will update this PR with your updates

**Comment by mpleung93** [comment]
Shoot I actually made them for the icons there and just put them in the wrong order.
But will do thank you

**Comment by mpleung93** [comment]
The icons were super cool thank you!
Mmk I just pushed the updated icons, that is enough for you to see it right? Or should I do anything else

**Comment by dylanmoz** [comment]
Looks good. Do you want the "Conclusion" feature to be the very first one though? Seems like that one should be the last one read.

**Comment by mpleung93** [comment]
good point one sec

**Pull request merged**
