### PR TITLE
edited product description

### PR DESCRIPTION
**Pull request by briannayamanaka**

### CODE REVIEW

**Comment by dylanmoz** [comment]
Please explain what the product actually is and how it works.

"our goal is to make the best leaders even better leaders and the best employees even better employees" does not sound too good.

If you make changes, do not remove this pull request. Don't close it, just leave it alone. Your changes you push to your master branch will update here

**Comment by briannayamanaka** [comment]
k

**Comment by briannayamanaka** [comment]
i jsut wanted to see what the button would do

i reopened it once i saw

**Comment by dylanmoz** [comment]
Change the name to Employee Survey

**Pull request merged**
